#!/bin/bash

# F1 ML Dashboard - Individual Agent Commands
# Copy and paste these commands to start each specialized agent

echo "🏎️ F1 ML Dashboard - Agent Deployment Commands"
echo "=============================================="
echo ""
echo "Copy and paste the commands below to initialize each agent:"
echo ""

echo "🔧 PHASE 1: Data Pipeline Specialist"
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│ cd /Users/jackmassey/Desktop/AI-Agent/F1-ML                │"
echo "│ echo '🚀 Starting Data Pipeline Specialist...'              │"
echo "│ open workspace/phase1/                                     │"
echo "│ cat tasks/phase1_data_pipeline.md                          │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""

echo "🏁 PHASE 2: Track Analysis Specialist"
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│ cd /Users/jackmassey/Desktop/AI-Agent/F1-ML                │"
echo "│ echo '🚀 Starting Track Analysis Specialist...'             │"
echo "│ open workspace/phase2/                                     │"
echo "│ cat tasks/phase2_track_analysis.md                         │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""

echo "👨‍🏁 PHASE 3: Driver Performance Analyst"
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│ cd /Users/jackmassey/Desktop/AI-Agent/F1-ML                │"
echo "│ echo '🚀 Starting Driver Performance Analyst...'            │"
echo "│ open workspace/phase3/                                     │"
echo "│ cat tasks/phase3_rookie_analysis.md                        │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""

echo "🤖 PHASE 4: ML Prediction Specialist"
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│ cd /Users/jackmassey/Desktop/AI-Agent/F1-ML                │"
echo "│ echo '🚀 Starting ML Prediction Specialist...'              │"
echo "│ open workspace/phase4/                                     │"
echo "│ cat tasks/phase4_silverstone_prediction.md                 │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""

echo "💻 PHASE 5: Frontend Integration Specialist"
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│ cd /Users/jackmassey/Desktop/AI-Agent/F1-ML                │"
echo "│ echo '🚀 Starting Frontend Integration Specialist...'       │"
echo "│ open workspace/phase5/                                     │"
echo "│ cat tasks/phase5_dashboard_integration.md                  │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""

echo "📊 MONITORING COMMANDS"
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│ # View all task files at once:                             │"
echo "│ find tasks/ -name '*.md' -exec echo '{}:' \\; -exec cat {} \\; │"
echo "│                                                             │"
echo "│ # Monitor all agent logs:                                  │"
echo "│ tail -f logs/agents/*.log                                  │"
echo "│                                                             │"
echo "│ # Check current 2025 season status:                       │"
echo "│ python3 data_pipeline/season_analysis.py                   │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""

echo "🎯 QUICK START - Initialize all workspaces:"
echo "chmod +x scripts/init_agents.sh && ./scripts/init_agents.sh"
